# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

bioc_packages: 'ComplexHeatmap'

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
